// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: grpc/picovpnd.proto

package picovpnd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddRequest) Reset() {
	*x = UserAddRequest{}
	mi := &file_grpc_picovpnd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddRequest) ProtoMessage() {}

func (x *UserAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_picovpnd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddRequest.ProtoReflect.Descriptor instead.
func (*UserAddRequest) Descriptor() ([]byte, []int) {
	return file_grpc_picovpnd_proto_rawDescGZIP(), []int{0}
}

func (x *UserAddRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserAddRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_grpc_picovpnd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_picovpnd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_grpc_picovpnd_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UserLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserLockRequest) Reset() {
	*x = UserLockRequest{}
	mi := &file_grpc_picovpnd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserLockRequest) ProtoMessage() {}

func (x *UserLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_picovpnd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserLockRequest.ProtoReflect.Descriptor instead.
func (*UserLockRequest) Descriptor() ([]byte, []int) {
	return file_grpc_picovpnd_proto_rawDescGZIP(), []int{2}
}

func (x *UserLockRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserUnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUnlockRequest) Reset() {
	*x = UserUnlockRequest{}
	mi := &file_grpc_picovpnd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUnlockRequest) ProtoMessage() {}

func (x *UserUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_picovpnd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUnlockRequest.ProtoReflect.Descriptor instead.
func (*UserUnlockRequest) Descriptor() ([]byte, []int) {
	return file_grpc_picovpnd_proto_rawDescGZIP(), []int{3}
}

func (x *UserUnlockRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeleteRequest) Reset() {
	*x = UserDeleteRequest{}
	mi := &file_grpc_picovpnd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeleteRequest) ProtoMessage() {}

func (x *UserDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_picovpnd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserDeleteRequest) Descriptor() ([]byte, []int) {
	return file_grpc_picovpnd_proto_rawDescGZIP(), []int{4}
}

func (x *UserDeleteRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

var File_grpc_picovpnd_proto protoreflect.FileDescriptor

const file_grpc_picovpnd_proto_rawDesc = "" +
	"\n" +
	"\x13grpc/picovpnd.proto\x12\bpicopvnd\"H\n" +
	"\x0eUserAddRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\" \n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"-\n" +
	"\x0fUserLockRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"/\n" +
	"\x11UserUnlockRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"/\n" +
	"\x11UserDeleteRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername2\x8e\x02\n" +
	"\x12OpenConnectService\x129\n" +
	"\aUserAdd\x12\x18.picopvnd.UserAddRequest\x1a\x12.picopvnd.Response\"\x00\x12;\n" +
	"\bUserLock\x12\x19.picopvnd.UserLockRequest\x1a\x12.picopvnd.Response\"\x00\x12?\n" +
	"\n" +
	"UserUnlock\x12\x1b.picopvnd.UserUnlockRequest\x1a\x12.picopvnd.Response\"\x00\x12?\n" +
	"\n" +
	"UserDelete\x12\x1b.picopvnd.UserDeleteRequest\x1a\x12.picopvnd.Response\"\x00B+Z)github.com/anatolio-deb/picovpnd/picovpndb\x06proto3"

var (
	file_grpc_picovpnd_proto_rawDescOnce sync.Once
	file_grpc_picovpnd_proto_rawDescData []byte
)

func file_grpc_picovpnd_proto_rawDescGZIP() []byte {
	file_grpc_picovpnd_proto_rawDescOnce.Do(func() {
		file_grpc_picovpnd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_picovpnd_proto_rawDesc), len(file_grpc_picovpnd_proto_rawDesc)))
	})
	return file_grpc_picovpnd_proto_rawDescData
}

var file_grpc_picovpnd_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpc_picovpnd_proto_goTypes = []any{
	(*UserAddRequest)(nil),    // 0: picopvnd.UserAddRequest
	(*Response)(nil),          // 1: picopvnd.Response
	(*UserLockRequest)(nil),   // 2: picopvnd.UserLockRequest
	(*UserUnlockRequest)(nil), // 3: picopvnd.UserUnlockRequest
	(*UserDeleteRequest)(nil), // 4: picopvnd.UserDeleteRequest
}
var file_grpc_picovpnd_proto_depIdxs = []int32{
	0, // 0: picopvnd.OpenConnectService.UserAdd:input_type -> picopvnd.UserAddRequest
	2, // 1: picopvnd.OpenConnectService.UserLock:input_type -> picopvnd.UserLockRequest
	3, // 2: picopvnd.OpenConnectService.UserUnlock:input_type -> picopvnd.UserUnlockRequest
	4, // 3: picopvnd.OpenConnectService.UserDelete:input_type -> picopvnd.UserDeleteRequest
	1, // 4: picopvnd.OpenConnectService.UserAdd:output_type -> picopvnd.Response
	1, // 5: picopvnd.OpenConnectService.UserLock:output_type -> picopvnd.Response
	1, // 6: picopvnd.OpenConnectService.UserUnlock:output_type -> picopvnd.Response
	1, // 7: picopvnd.OpenConnectService.UserDelete:output_type -> picopvnd.Response
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_picovpnd_proto_init() }
func file_grpc_picovpnd_proto_init() {
	if File_grpc_picovpnd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_picovpnd_proto_rawDesc), len(file_grpc_picovpnd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_picovpnd_proto_goTypes,
		DependencyIndexes: file_grpc_picovpnd_proto_depIdxs,
		MessageInfos:      file_grpc_picovpnd_proto_msgTypes,
	}.Build()
	File_grpc_picovpnd_proto = out.File
	file_grpc_picovpnd_proto_goTypes = nil
	file_grpc_picovpnd_proto_depIdxs = nil
}
